CREATE DATABASE testdb;
USE testdb;
CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);
SHOW TABLES;
DESCRIBE user;
SHOW DATABASES;
SELECT * FROM user;

